### ISSUE TITLE
Convert pptx files to pdf.

### ISSUE THREAD

**Issue by jeremyong** [CppCon/CppCon2015#3]
I hope this doesn't come off as unappreciative of the work done by the presenters (who all did wonderfully). However, I think it might not be unreasonable to request that authors export their presentations in a format that is more open and easily accessible for broader viewership.

**Comment by sdutoit** [comment]
We've [asked the speakers](https://github.com/CppCon/CppCon2015/blob/master/Submitting.md) to, preferably, send their files as PDF, and most have. [The index](https://github.com/CppCon/CppCon2015/blob/master/README.md) is also set up so that it prefers to link (the title of the session) to a PDF when one exists.

Generally the presenters that haven't sent PDFs mentioned specific reasons why they didn't (mostly due to animations they wished to preserve).

So, while I completely empathize with your request, I'm not sure there is much more to be done here, sorry!
